name: "Godeps Action"
description: "Create pull requests for dependnecy updates (better than dependantbot)"
author: "Kevin Mulvey"
inputs:
  packages:
    description: 'Create pull requests for dependnecy updates (better than dependantbot).'
    required: false
    default: './...'

runs:
  using: 'composite'
  steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go 
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
    - name: Run godeps
      env: GITHUB_TOKEN: ${{ github.token }}
      run: go run cmd/main.go
      shell: bash

branding:
  icon: 'alert-triangle'
  color: 'red'
